Updated github workflow document
sandialabs/pyttb pull request #123
Opened 2023-06-01 20:29 UTC by DeepBlockDeepak

Hey, @ntjohnson1 . What do you think?

2023-06-01 20:53 UTC, ntjohnson1 requested changes
A couple of minor things but otherwise looks good to me. As I mentioned on the previous review I would lean towards dropping all the external links but I could see including them being more user friendly to subject matter experts who don't spend as much time on github.

1. Not super critical here but good to err on the side of a more verbose PR description in case someone is back tracking through the history in the future. We have the link to the issue with lots of discussion, but a summary here to avoid the need to click into that is usually appreciate when I end up putting on my archeologist hat for something.
2. Left a nit about the period.
3. This whole thing should be appended as an additional sub-section to the `CONTRIBUTING.md` to simplify needing to look around. Basically that one page should be enough for someone to figure out how to submit to the repo https://github.com/sandialabs/pyttb/contribute

2023-06-01 20:53 UTC, ntjohnson1 commented on WORKFLOW.md
> +    - See GitHub's [Getting Started Guide](https://docs.github.com/en/get-started/quickstart/fork-a-repo)
NIT: Everything else ends with a period.

```suggestion
    - See GitHub's [Getting Started Guide](https://docs.github.com/en/get-started/quickstart/fork-a-repo).
```

2023-06-02 02:29 UTC, DeepBlockDeepak commented
I got rid of the external links, and appended the slightly revised file to the end of CONTRIBUTING.md. I'm a bit fuzzy on the forking process but I think that the details are accurate.

2023-06-02 03:30 UTC, dmdunla approved these changes

2023-06-02 03:31 UTC, dmdunla approved these changes

2023-06-02 09:31 UTC, ntjohnson1 approved these changes

2023-06-02 09:46 UTC, ntjohnson1 commented
> I'm a bit fuzzy on the forking process but I think that the details are accurate.

Just for your own experience it might be worth opening a PR for some small change at some point via the fork and submit approach. That's how I do all of my work here if you want to look at any of my closed PRs for an example.

2023-06-02 23:57 UTC, merged