First pass at HOSVD tutorial. Some outputs are inconsistent with MATL…
sandialabs/pyttb pull request #247
Opened 2023-09-19 06:13 UTC by jeremy-myers

…AB, so some work still remains to understand where the source of error is coming from.

2023-09-19 19:37 UTC, ntjohnson1 commented
I'll let Danny review the PR but wanted to see if you had issues building the documentation locally. Following the contributing guide and running the sphinx build should also build the docs to locally validate tutorial changes/additions. Just figured your fresh set of eyes would be good to check that. It looks like your type hint was using python >=3.9 `tuple` where I believe readthedocs uses 3.8 `from typing import Tuple`. In which case the badge on the readme should update to show we support 3.8 once we release a new pypi package.

2023-09-19 20:27 UTC, jeremy-myers commented
> I'll let Danny review the PR but wanted to see if you had issues building the documentation locally. Following the contributing guide and running the sphinx build should also build the docs to locally validate tutorial changes/additions. Just figured your fresh set of eyes would be good to check that. It looks like your type hint was using python >=3.9 `tuple` where I believe readthedocs uses 3.8 `from typing import Tuple`. In which case the badge on the readme should update to show we support 3.8 once we release a new pypi package.

I dropped the type hinting that caused the error. But I just experienced issues building the documentation locally. I'll open up an issue.

2023-09-27 19:32 UTC, dmdunla requested changes

2023-09-27 19:32 UTC, dmdunla commented on docs/source/tutorial/HOSVD.ipynb
> +    "# Create random 50 x 40 x 30 tensor with 5 x 4 x 3 core\n",
# Create random tensor of shape (50, 40, 30) with core of shape (5, 4, 3)\n"

NOTE: change all other occurrences in the text of "size" to "shape" and use tuples to show the specific shapes.

2023-09-27 19:32 UTC, dmdunla commented on docs/source/tutorial/HOSVD.ipynb
> +    "Similarly, lhe norm squared of the first block of G is 0.9, so specifying an error of `1e-1` *should* result in a core of size $3 \\times 2 \\times 1$"
Similarly, the norm

2023-09-27 19:32 UTC, dmdunla commented on docs/source/tutorial/HOSVD.ipynb
> + "metadata": {
Run the following before finalizing (from #208 which has not yet landed):

```
nbstripout docs/source/tutorial/class_ttensor.ipynb \
--extra-keys "metadata.language_info metadata.vscode metadata.kernelspec"
```

2023-09-27 19:36 UTC, dmdunla commented
When I run the blocks with `hosvd`, the output contains output as follows:

```
 Size of core: (7, 7, 7)
```

@jeremy-myers Can you add an Issue to change this to the following? (Remove the initial space and change "Size" to "Shape")

```
Shape of core: (7, 7, 7)
```

2023-09-27 21:57 UTC, dmdunla approved these changes

2023-09-27 21:57 UTC, merged