Fixing tests to put quotes around path
sandialabs/pyttb pull request #379
Opened 2024-12-30 22:25 UTC by tgkolda

Some tests were failing for me because my path names have spaces. This is a fix for that. Fixes #378 .

2025-01-31 17:01 UTC, dmdunla requested changes

2025-01-31 17:01 UTC, dmdunla commented on tests/test_package.py
> +        f'mypy -p pyttb  --config-file "{toml_file}" {skip_untyped}',
Can you reverse the use of the quotation types to align with other f-strings throughout `pyttb`? Will that work on Windows?

```python
f"mypy -p pyttb  --config-file '{toml_file}' '{skip_untyped}'",
```

2025-01-31 20:11 UTC, tgkolda commented on tests/test_package.py
> +        f'ruff check "{root_dir}" --config "{toml_file}"',
This works

2025-01-31 20:15 UTC, tgkolda commented on tests/test_package.py
> +        f'ruff check "{root_dir}" --config "{toml_file}"',
Alas, this change didn't work for me. Not sure why.

2025-01-31 20:19 UTC, dmdunla commented
Can you update your branch and then I’ll be able to run the tests from the GitHub interface?
________________________________
From: Tammy Kolda ***@***.***>
Sent: Friday, January 31, 2025 1:16:05 PM
To: sandialabs/pyttb ***@***.***>
Cc: Dunlavy, Danny ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/pyttb] Fixing tests to put quotes around path (PR #379)


@tgkolda commented on this pull request.

________________________________

In tests/test_package.py<https://github.com/sandialabs/pyttb/pull/379#discussion_r1937938074>:

> @@ -21,7 +21,7 @@ def test_linting():
     root_dir = os.path.dirname(os.path.dirname(__file__))
     toml_file = os.path.join(root_dir, "pyproject.toml")
     subprocess.run(
-        f"ruff check {root_dir} --config {toml_file}",
+        f'ruff check "{root_dir}" --config "{toml_file}"',


Alas, this change didn't work for me. Not sure why.

—
Reply to this email directly, view it on GitHub<https://github.com/sandialabs/pyttb/pull/379#discussion_r1937938074>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHIY2IRWIJJVCLC5LR3XX4D2NPKYLAVCNFSM6AAAAABUMUZFOOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKOBXHAYDENJUGU>.
You are receiving this because you commented.Message ID: ***@***.***>

2025-01-31 20:49 UTC, dmdunla commented on tests/test_package.py
> +        f'ruff format --check "{root_dir}" --config "{toml_file}"',
f"ruff format --check \"{root_dir}\" --config \"{toml_file}\"",

2025-01-31 20:51 UTC, dmdunla commented on tests/test_package.py
> +        f'ruff format --check "{root_dir}" --config "{toml_file}"',
Need the quotes for Windows

2025-01-31 20:51 UTC, dmdunla commented on tests/test_package.py
> +        f'ruff check "{root_dir}" --config "{toml_file}"',
Need the quotes for Windows

2025-01-31 20:51 UTC, dmdunla commented on tests/test_package.py
> +        f'mypy -p pyttb  --config-file "{toml_file}" {skip_untyped}',
Need the quotes for Windows

2025-01-31 20:52 UTC, dmdunla approved these changes
Need the quotes for Windows

2025-02-02 23:44 UTC, tgkolda commented
@dmdunla I've updated the quote patterns so that there are double quotes on the outside and the inner quotes are escaped, i.e., `\"`. However, in doing so, my systems would only pass the tests if I let ruff make a bunch of changes. That is most of what is in this branch. FWIW, I am running I am using Python 3.11.11 and ruff version 0.7.4. Ruff was installed using the instructions for developers, i.e., with the command `python -m pip install -e ".[dev,doc]"` (see #387 for my it is preceded by `python -m`).

2025-02-03 00:23 UTC, tgkolda commented
I'm closing this because it seems to be contaminated in a way. Starting a fresh PR instead.

2025-02-03 00:23 UTC, closed without merging